### ISSUE TITLE
stupid this no working fix it or die

### ISSUE THREAD

**Issue by 4k0** [dariopf/Discord-Moneybot-Unbelievaboat#1]
C:\Users\Administrator\Downloads\Discord-Moneybot-Unbelievaboat-main (1)\Discord-Moneybot-Unbelievaboat-main\discord-moneybot.py"
  File "C:\Users\Administrator\Downloads\Discord-Moneybot-Unbelievaboat-main (1)\Discord-Moneybot-Unbelievaboat-main\discord-moneybot.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file C:\Users\Administrator\Downloads\Discord-Moneybot-Unbelievaboat-main (1)\Discord-Moneybot-Unbelievaboat-main\discord-moneybot.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by dariopf** [comment]
Hi, there are some problems because the code is old its updated in 0,02 https://github.com/dariopf/Discord-Moneybot-Unbelievaboat/releases/tag/0%2C02
The problem is that chrome driver needs to update when you uptdate chrome so go to he chrome web driver and download the correct version for you, I uploaded for Chrome 99 windows. Other thing is that now when you try to login discord needs to make a captcha and some people have 2fa so now you can't login without see anything(i will solve it in future versions), the chrome tab appears and you need to complete the captcha. Thanks :)
